Contact enhance
serum-390/soen390-team16-godzilla pull request #142
Opened 2021-03-07 17:33 UTC by shushengfuqin

# Description

add vender contact  domain, repository, handler, router.
in the repository there are query modification for findAll, findById, and update. they are made for vender. where in the query they will hard code the contact_type to vender. 
ex. findAll -> findAllVender 

Test are still in working.

2021-03-07 22:46 UTC, instamine approved these changes
VenderContactRouter and venderContactHandler looks good.

2021-03-08 00:36 UTC, obonobo requested changes

2021-03-08 00:43 UTC, shushengfuqin commented on src/main/java/ca/serum390/godzilla/data/repositories/VenderContactRepository.java
> +    //Update sales contact where contact_type = vendor
done

2021-03-08 00:45 UTC, obonobo approved these changes
Looks good, just clean up the comments

2021-03-08 00:50 UTC, shushengfuqin commented on src/main/java/ca/serum390/godzilla/data/repositories/VenderContactRepository.java
> +            String string, Integer id);
it should be contactType. 
I took it out

2021-03-08 00:51 UTC, shushengfuqin commented on src/main/java/ca/serum390/godzilla/data/repositories/VenderContactRepository.java
> +    /**
@Repository added

2021-03-08 00:52 UTC, shushengfuqin commented on src/main/java/ca/serum390/godzilla/data/repositories/VenderContactRepository.java
> +    //Find all customer
done

2021-03-08 00:52 UTC, shushengfuqin commented on src/main/java/ca/serum390/godzilla/api/handlers/VenderContactHandler.java
> +    //get all vender contact
done

2021-03-08 01:05 UTC, shushengfuqin commented on src/main/java/ca/serum390/godzilla/api/handlers/VenderContactHandler.java
> +public class VenderContactHandler {
done

2021-03-08 01:49 UTC, shushengfuqin commented on src/main/java/ca/serum390/godzilla/api/handlers/VenderContactHandler.java
> +    //get all vender contact
done

2021-03-08 01:49 UTC, shushengfuqin commented on src/main/java/ca/serum390/godzilla/data/repositories/VenderContactRepository.java
> +    //Find all customer
done

2021-03-08 02:03 UTC, merged